// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [HsmManagement.ApproveSingleTenantHsmInstanceProposal][google.cloud.kms.v1.HsmManagement.ApproveSingleTenantHsmInstanceProposal].
///
/// [google.cloud.kms.v1.HsmManagement.ApproveSingleTenantHsmInstanceProposal]: <doc:HsmManagementClient/approveSingleTenantHsmInstanceProposal(request:options:)>
public struct ApproveSingleTenantHsmInstanceProposalRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The
  /// [name][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.name] of the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
  /// to approve.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.name]: <doc:SingleTenantHsmInstanceProposal/name>
  public var name: Swift.String = Swift.String()

  /// The approval payload. The type of approval payload must correspond to the
  /// type of approval_parameters in the proposal.
  public var approvalPayload: OneOf_ApprovalPayload? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApproveSingleTenantHsmInstanceProposalRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApproveSingleTenantHsmInstanceProposalRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let quorumReply = CodingKeys(stringValue: "quorumReply")
    static let requiredActionQuorumReply = CodingKeys(stringValue: "requiredActionQuorumReply")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "quorumReply",
      "requiredActionQuorumReply",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }

    var approvalPayload: OneOf_ApprovalPayload? = nil
    let approvalPayloadCheckAndSet = {
      if approvalPayload != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'approvalPayload'"))
      }
      approvalPayload = $0
    }
    if let quorumReply = try container.decodeIfPresent(
      ApproveSingleTenantHsmInstanceProposalRequest.QuorumReply?.self, forKey: .quorumReply)
    {
      try approvalPayloadCheckAndSet(.quorumReply(quorumReply))
    }
    if let requiredActionQuorumReply = try container.decodeIfPresent(
      ApproveSingleTenantHsmInstanceProposalRequest.RequiredActionQuorumReply?.self,
      forKey: .requiredActionQuorumReply)
    {
      try approvalPayloadCheckAndSet(.requiredActionQuorumReply(requiredActionQuorumReply))
    }
    self.approvalPayload = approvalPayload
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.approvalPayload {
      switch choice {
      case .quorumReply(let value):
        try container.encode(value, forKey: .quorumReply)
      case .requiredActionQuorumReply(let value):
        try container.encode(value, forKey: .requiredActionQuorumReply)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The reply to
  /// [QuorumParameters][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.QuorumParameters]
  /// for approving the proposal.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.QuorumParameters]: <doc:SingleTenantHsmInstanceProposal/QuorumParameters>
  public struct QuorumReply: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The challenge replies to approve the proposal. Challenge
    /// replies can be sent across multiple requests. The proposal will be
    /// approved when
    /// [required_approver_count][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.QuorumParameters.required_approver_count]
    /// challenge replies are provided.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.QuorumParameters.required_approver_count]: <doc:SingleTenantHsmInstanceProposal/QuorumParameters/requiredApproverCount>
    public var challengeReplies: [ChallengeReply] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `QuorumReply`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QuorumReply().with { $0.challengeReplies = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let challengeReplies = CodingKeys(stringValue: "challengeReplies")

      static let _knownKeys: Set<Swift.String> = [
        "challengeReplies"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([ChallengeReply].self, forKey: .challengeReplies)
      {
        self.challengeReplies = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.challengeReplies, forKey: .challengeReplies)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.ApproveSingleTenantHsmInstanceProposalRequest.QuorumReply"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The reply to
  /// [RequiredActionQuorumParameters][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters]
  /// for approving the proposal.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters]: <doc:SingleTenantHsmInstanceProposal/RequiredActionQuorumParameters>
  public struct RequiredActionQuorumReply: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. All required challenges must be signed for the proposal to be
    /// approved. These can be sent across multiple requests.
    public var requiredChallengeReplies: [ChallengeReply] = []

    /// Required. Quorum members' signed challenge replies. These can be provided
    /// across multiple requests. The proposal will be approved when
    /// [required_approver_count][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters.required_approver_count]
    /// quorum_challenge_replies are provided and when all
    /// required_challenge_replies are provided.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters.required_approver_count]: <doc:SingleTenantHsmInstanceProposal/RequiredActionQuorumParameters/requiredApproverCount>
    public var quorumChallengeReplies: [ChallengeReply] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `RequiredActionQuorumReply`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RequiredActionQuorumReply().with { $0.requiredChallengeReplies = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let requiredChallengeReplies = CodingKeys(stringValue: "requiredChallengeReplies")
      static let quorumChallengeReplies = CodingKeys(stringValue: "quorumChallengeReplies")

      static let _knownKeys: Set<Swift.String> = [
        "requiredChallengeReplies",
        "quorumChallengeReplies",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [ChallengeReply].self, forKey: .requiredChallengeReplies)
      {
        self.requiredChallengeReplies = value
      }
      if let value = try container.decodeIfPresent(
        [ChallengeReply].self, forKey: .quorumChallengeReplies)
      {
        self.quorumChallengeReplies = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.requiredChallengeReplies, forKey: .requiredChallengeReplies)
      try container.encode(self.quorumChallengeReplies, forKey: .quorumChallengeReplies)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.ApproveSingleTenantHsmInstanceProposalRequest.RequiredActionQuorumReply"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The approval payload. The type of approval payload must correspond to the
  /// type of approval_parameters in the proposal.
  public enum OneOf_ApprovalPayload: Codable, Equatable, Sendable {
    /// Required. The reply to
    /// [QuorumParameters][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.QuorumParameters]
    /// for approving the proposal.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.QuorumParameters]: <doc:SingleTenantHsmInstanceProposal/QuorumParameters>
    indirect case quorumReply(ApproveSingleTenantHsmInstanceProposalRequest.QuorumReply?)
    /// Required. The reply to
    /// [RequiredActionQuorumParameters][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters]
    /// for approving the proposal.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters]: <doc:SingleTenantHsmInstanceProposal/RequiredActionQuorumParameters>
    indirect case requiredActionQuorumReply(
      ApproveSingleTenantHsmInstanceProposalRequest.RequiredActionQuorumReply?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.ApproveSingleTenantHsmInstanceProposalRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
