// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A [Certificate][google.cloud.kms.v1.Certificate] represents an X.509
/// certificate used to authenticate HTTPS connections to EKM replicas.
///
/// [google.cloud.kms.v1.Certificate]: <doc:Certificate>
public struct Certificate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The raw certificate bytes in DER format.
  public var rawDer: Foundation.Data = Foundation.Data()

  /// Output only. True if the certificate was parsed successfully.
  public var parsed: Swift.Bool = Swift.Bool()

  /// Output only. The issuer distinguished name in RFC 2253 format. Only present
  /// if [parsed][google.cloud.kms.v1.Certificate.parsed] is true.
  ///
  /// [google.cloud.kms.v1.Certificate.parsed]: <doc:Certificate/parsed>
  public var issuer: Swift.String = Swift.String()

  /// Output only. The subject distinguished name in RFC 2253 format. Only
  /// present if [parsed][google.cloud.kms.v1.Certificate.parsed] is true.
  ///
  /// [google.cloud.kms.v1.Certificate.parsed]: <doc:Certificate/parsed>
  public var subject: Swift.String = Swift.String()

  /// Output only. The subject Alternative DNS names. Only present if
  /// [parsed][google.cloud.kms.v1.Certificate.parsed] is true.
  ///
  /// [google.cloud.kms.v1.Certificate.parsed]: <doc:Certificate/parsed>
  public var subjectAlternativeDnsNames: [Swift.String] = []

  /// Output only. The certificate is not valid before this time. Only present if
  /// [parsed][google.cloud.kms.v1.Certificate.parsed] is true.
  ///
  /// [google.cloud.kms.v1.Certificate.parsed]: <doc:Certificate/parsed>
  public var notBeforeTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The certificate is not valid after this time. Only present if
  /// [parsed][google.cloud.kms.v1.Certificate.parsed] is true.
  ///
  /// [google.cloud.kms.v1.Certificate.parsed]: <doc:Certificate/parsed>
  public var notAfterTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The certificate serial number as a hex string. Only present if
  /// [parsed][google.cloud.kms.v1.Certificate.parsed] is true.
  ///
  /// [google.cloud.kms.v1.Certificate.parsed]: <doc:Certificate/parsed>
  public var serialNumber: Swift.String = Swift.String()

  /// Output only. The SHA-256 certificate fingerprint as a hex string. Only
  /// present if [parsed][google.cloud.kms.v1.Certificate.parsed] is true.
  ///
  /// [google.cloud.kms.v1.Certificate.parsed]: <doc:Certificate/parsed>
  public var sha256Fingerprint: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Certificate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Certificate().with { $0.rawDer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let rawDer = CodingKeys(stringValue: "rawDer")
    static let parsed = CodingKeys(stringValue: "parsed")
    static let issuer = CodingKeys(stringValue: "issuer")
    static let subject = CodingKeys(stringValue: "subject")
    static let subjectAlternativeDnsNames = CodingKeys(stringValue: "subjectAlternativeDnsNames")
    static let notBeforeTime = CodingKeys(stringValue: "notBeforeTime")
    static let notAfterTime = CodingKeys(stringValue: "notAfterTime")
    static let serialNumber = CodingKeys(stringValue: "serialNumber")
    static let sha256Fingerprint = CodingKeys(stringValue: "sha256Fingerprint")

    static let _knownKeys: Set<Swift.String> = [
      "rawDer",
      "parsed",
      "issuer",
      "subject",
      "subjectAlternativeDnsNames",
      "notBeforeTime",
      "notAfterTime",
      "serialNumber",
      "sha256Fingerprint",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .rawDer) {
      self.rawDer = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .parsed) {
      self.parsed = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .issuer) {
      self.issuer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subject) {
      self.subject = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .subjectAlternativeDnsNames)
    {
      self.subjectAlternativeDnsNames = value
    }
    self.notBeforeTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .notBeforeTime)
    self.notAfterTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .notAfterTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serialNumber) {
      self.serialNumber = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sha256Fingerprint) {
      self.sha256Fingerprint = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.rawDer, forKey: .rawDer)
    try container.encode(self.parsed, forKey: .parsed)
    try container.encode(self.issuer, forKey: .issuer)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.subjectAlternativeDnsNames, forKey: .subjectAlternativeDnsNames)
    try container.encodeIfPresent(self.notBeforeTime, forKey: .notBeforeTime)
    try container.encodeIfPresent(self.notAfterTime, forKey: .notAfterTime)
    try container.encode(self.serialNumber, forKey: .serialNumber)
    try container.encode(self.sha256Fingerprint, forKey: .sha256Fingerprint)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.Certificate"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
