// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Data with integrity verification field.
public struct ChecksummedData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Raw Data.
  public var data: Foundation.Data = Foundation.Data()

  /// Integrity verification field. A CRC32C
  /// checksum of the returned
  /// [ChecksummedData.data][google.cloud.kms.v1.ChecksummedData.data]. An
  /// integrity check of
  /// [ChecksummedData.data][google.cloud.kms.v1.ChecksummedData.data] can be
  /// performed by computing the CRC32C checksum of
  /// [ChecksummedData.data][google.cloud.kms.v1.ChecksummedData.data] and
  /// comparing your results to this field. Discard the response in case of
  /// non-matching checksum values, and perform a limited number of retries. A
  /// persistent mismatch may indicate an issue in your computation of the CRC32C
  /// checksum. Note: This field is defined as int64 for reasons of compatibility
  /// across different languages. However, it is a non-negative integer, which
  /// will never exceed `2^32-1`, and can be safely downconverted to uint32 in
  /// languages that support this type.
  ///
  /// [google.cloud.kms.v1.ChecksummedData.data]: <doc:ChecksummedData/data>
  public var crc32CChecksum: GoogleWKT.WKTInt64Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ChecksummedData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChecksummedData().with { $0.data = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let data = CodingKeys(stringValue: "data")
    static let crc32CChecksum = CodingKeys(stringValue: "crc32cChecksum")

    static let _knownKeys: Set<Swift.String> = [
      "data",
      "crc32cChecksum",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .data) {
      self.data = value
    }
    self.crc32CChecksum = try container.decodeIfPresent(
      GoogleWKT.WKTInt64Value.self, forKey: .crc32CChecksum)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.data, forKey: .data)
    try container.encodeIfPresent(self.crc32CChecksum, forKey: .crc32CChecksum)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.ChecksummedData"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
