// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [HsmManagement.CreateSingleTenantHsmInstance][google.cloud.kms.v1.HsmManagement.CreateSingleTenantHsmInstance].
///
/// [google.cloud.kms.v1.HsmManagement.CreateSingleTenantHsmInstance]: <doc:HsmManagementClient/createSingleTenantHsmInstance(request:options:)>
public struct CreateSingleTenantHsmInstanceRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the location associated with the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance], in
  /// the format `projects/*/locations/*`.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  public var parent: Swift.String = Swift.String()

  /// Optional. It must be unique within a location and match the regular
  /// expression `[a-zA-Z0-9_-]{1,63}`.
  public var singleTenantHsmInstanceId: Swift.String = Swift.String()

  /// Required. An
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] with
  /// initial field values.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  public var singleTenantHsmInstance: SingleTenantHsmInstance? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateSingleTenantHsmInstanceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateSingleTenantHsmInstanceRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let singleTenantHsmInstanceId = CodingKeys(stringValue: "singleTenantHsmInstanceId")
    static let singleTenantHsmInstance = CodingKeys(stringValue: "singleTenantHsmInstance")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "singleTenantHsmInstanceId",
      "singleTenantHsmInstance",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .singleTenantHsmInstanceId)
    {
      self.singleTenantHsmInstanceId = value
    }
    self.singleTenantHsmInstance = try container.decodeIfPresent(
      SingleTenantHsmInstance.self, forKey: .singleTenantHsmInstance)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.singleTenantHsmInstanceId, forKey: .singleTenantHsmInstanceId)
    try container.encodeIfPresent(self.singleTenantHsmInstance, forKey: .singleTenantHsmInstance)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.CreateSingleTenantHsmInstanceRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
