// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [KeyManagementService.Decapsulate][google.cloud.kms.v1.KeyManagementService.Decapsulate].
///
/// [google.cloud.kms.v1.KeyManagementService.Decapsulate]: <doc:KeyManagementServiceClient/decapsulate(request:options:)>
public struct DecapsulateRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] to use for
  /// decapsulation.
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  public var name: Swift.String = Swift.String()

  /// Required. The ciphertext produced from encapsulation with the
  /// named [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] public
  /// key(s).
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  public var ciphertext: Foundation.Data = Foundation.Data()

  /// Optional. A CRC32C checksum of the
  /// [DecapsulateRequest.ciphertext][google.cloud.kms.v1.DecapsulateRequest.ciphertext].
  /// If specified,
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// verify the integrity of the received
  /// [DecapsulateRequest.ciphertext][google.cloud.kms.v1.DecapsulateRequest.ciphertext]
  /// using this checksum.
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// report an error if the checksum verification fails. If you receive a
  /// checksum error, your client should verify that
  /// CRC32C([DecapsulateRequest.ciphertext][google.cloud.kms.v1.DecapsulateRequest.ciphertext])
  /// is equal to
  /// [DecapsulateRequest.ciphertext_crc32c][google.cloud.kms.v1.DecapsulateRequest.ciphertext_crc32c],
  /// and if so, perform a limited number of retries. A persistent mismatch may
  /// indicate an issue in your computation of the CRC32C checksum. Note: This
  /// field is defined as int64 for reasons of compatibility across different
  /// languages. However, it is a non-negative integer, which will never exceed
  /// 2^32-1, and can be safely downconverted to uint32 in languages that support
  /// this type.
  ///
  /// [google.cloud.kms.v1.DecapsulateRequest.ciphertext]: <doc:DecapsulateRequest/ciphertext>
  /// [google.cloud.kms.v1.DecapsulateRequest.ciphertext_crc32c]: <doc:DecapsulateRequest/ciphertextCrc32C>
  /// [google.cloud.kms.v1.KeyManagementService]: <doc:KeyManagementServiceClient>
  public var ciphertextCrc32C: GoogleWKT.Int64Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DecapsulateRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DecapsulateRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let ciphertext = CodingKeys(stringValue: "ciphertext")
    static let ciphertextCrc32C = CodingKeys(stringValue: "ciphertextCrc32c")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "ciphertext",
      "ciphertextCrc32c",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .ciphertext) {
      self.ciphertext = value
    }
    self.ciphertextCrc32C = try container.decodeIfPresent(
      GoogleWKT.Int64Value.self, forKey: .ciphertextCrc32C)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.ciphertext, forKey: .ciphertext)
    try container.encodeIfPresent(self.ciphertextCrc32C, forKey: .ciphertextCrc32C)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.DecapsulateRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
