// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class EkmServiceLogging: EkmServiceStub {
    let inner: any EkmServiceStub
    let logger: Logger

    public init(_ inner: any EkmServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-kms-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudkms"
      logger[metadataKey: "gcp.experimental.swift.client"] = "EkmService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listEkmConnections(
      request: ListEkmConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListEkmConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEkmConnections",
        action: {
          (r: ListEkmConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ListEkmConnectionsResponse
          in
          return try await self.inner.listEkmConnections(request: r, options: o)
        })
    }

    public func getEkmConnection(
      request: GetEkmConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.EkmConnection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEkmConnection",
        action: {
          (r: GetEkmConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.EkmConnection
          in
          return try await self.inner.getEkmConnection(request: r, options: o)
        })
    }

    public func createEkmConnection(
      request: CreateEkmConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.EkmConnection {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEkmConnection",
        action: {
          (r: CreateEkmConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.EkmConnection
          in
          return try await self.inner.createEkmConnection(request: r, options: o)
        })
    }

    public func updateEkmConnection(
      request: UpdateEkmConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.EkmConnection {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEkmConnection",
        action: {
          (r: UpdateEkmConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.EkmConnection
          in
          return try await self.inner.updateEkmConnection(request: r, options: o)
        })
    }

    public func getEkmConfig(
      request: GetEkmConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.EkmConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEkmConfig",
        action: {
          (r: GetEkmConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.EkmConfig
          in
          return try await self.inner.getEkmConfig(request: r, options: o)
        })
    }

    public func updateEkmConfig(
      request: UpdateEkmConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.EkmConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEkmConfig",
        action: {
          (r: UpdateEkmConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.EkmConfig
          in
          return try await self.inner.updateEkmConfig(request: r, options: o)
        })
    }

    public func verifyConnectivity(
      request: VerifyConnectivityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.VerifyConnectivityResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "verifyConnectivity",
        action: {
          (r: VerifyConnectivityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.VerifyConnectivityResponse
          in
          return try await self.inner.verifyConnectivity(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
