// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ExternalProtectionLevelOptions stores a group of additional fields for
/// configuring a [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] that
/// are specific to the [EXTERNAL][google.cloud.kms.v1.ProtectionLevel.EXTERNAL]
/// protection level and
/// [EXTERNAL_VPC][google.cloud.kms.v1.ProtectionLevel.EXTERNAL_VPC] protection
/// levels.
///
/// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
/// [google.cloud.kms.v1.ProtectionLevel.EXTERNAL]: <doc:ProtectionLevel/external>
/// [google.cloud.kms.v1.ProtectionLevel.EXTERNAL_VPC]: <doc:ProtectionLevel/externalVpc>
public struct ExternalProtectionLevelOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The URI for an external resource that this
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] represents.
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  public var externalKeyUri: Swift.String = Swift.String()

  /// Optional. The path to the external key material on the EKM when using
  /// [EkmConnection][google.cloud.kms.v1.EkmConnection] e.g., "v0/my/key". Set
  /// this field instead of external_key_uri when using an
  /// [EkmConnection][google.cloud.kms.v1.EkmConnection].
  ///
  /// [google.cloud.kms.v1.EkmConnection]: <doc:EkmConnection>
  public var ekmConnectionKeyPath: Swift.String = Swift.String()

  /// Optional. The resource name of the backend environment where the key
  /// material of [CryptoKeyVersions][google.cloud.kms.v1.CryptoKeyVersion] is
  /// associated with. Setting this field overrides the [CryptoKeyBackend][].
  /// This field may be set when
  /// [CryptoKeyVersions][google.cloud.kms.v1.CryptoKeyVersion] is set to
  /// [EXTERNAL_VPC][google.cloud.kms.v1.ProtectionLevel.EXTERNAL_VPC]. Format:
  /// `projects/*/locations/*/ekmConnections/*`.
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  /// [google.cloud.kms.v1.ProtectionLevel.EXTERNAL_VPC]: <doc:ProtectionLevel/externalVpc>
  public var ekmConnectionBackendOverride: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExternalProtectionLevelOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExternalProtectionLevelOptions().with { $0.externalKeyUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let externalKeyUri = CodingKeys(stringValue: "externalKeyUri")
    static let ekmConnectionKeyPath = CodingKeys(stringValue: "ekmConnectionKeyPath")
    static let ekmConnectionBackendOverride = CodingKeys(
      stringValue: "ekmConnectionBackendOverride")

    static let _knownKeys: Set<Swift.String> = [
      "externalKeyUri",
      "ekmConnectionKeyPath",
      "ekmConnectionBackendOverride",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .externalKeyUri) {
      self.externalKeyUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ekmConnectionKeyPath) {
      self.ekmConnectionKeyPath = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .ekmConnectionBackendOverride)
    {
      self.ekmConnectionBackendOverride = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.externalKeyUri, forKey: .externalKeyUri)
    try container.encode(self.ekmConnectionKeyPath, forKey: .ekmConnectionKeyPath)
    try container.encode(self.ekmConnectionBackendOverride, forKey: .ekmConnectionBackendOverride)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.ExternalProtectionLevelOptions"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
