// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [KeyManagementService.GetImportJob][google.cloud.kms.v1.KeyManagementService.GetImportJob].
///
/// [google.cloud.kms.v1.KeyManagementService.GetImportJob]: <doc:KeyManagementServiceClient/getImportJob(request:options:)>
public struct GetImportJobRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The [name][google.cloud.kms.v1.ImportJob.name] of the
  /// [ImportJob][google.cloud.kms.v1.ImportJob] to get.
  ///
  /// [google.cloud.kms.v1.ImportJob]: <doc:ImportJob>
  /// [google.cloud.kms.v1.ImportJob.name]: <doc:ImportJob/name>
  public var name: Swift.String = Swift.String()

  /// Optional. Specifies the [WrappingPublicKey][] format.
  /// If not specified:
  ///   * For RSA-based import methods, the wrapping key will be returned in PEM
  ///   format
  ///   * For pure ML-KEM-based import methods, the wrapping key will be returned
  ///   in the raw bytes format specified in FIPS-203
  ///   * For X-Wing-based import methods, the wrapping key will be returned in
  ///   the raw bytes format specified in
  ///   https://datatracker.ietf.org/doc/draft-connolly-cfrg-xwing-kem.
  public var publicKeyFormat: PublicKey.PublicKeyFormat = PublicKey.PublicKeyFormat()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GetImportJobRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GetImportJobRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let publicKeyFormat = CodingKeys(stringValue: "publicKeyFormat")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "publicKeyFormat",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      PublicKey.PublicKeyFormat.self, forKey: .publicKeyFormat)
    {
      self.publicKeyFormat = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.publicKeyFormat, forKey: .publicKeyFormat)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.GetImportJobRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
