// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol HsmManagementStub: Sendable {
    func listSingleTenantHsmInstances(
      request: ListSingleTenantHsmInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListSingleTenantHsmInstancesResponse

    func getSingleTenantHsmInstance(
      request: GetSingleTenantHsmInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.SingleTenantHsmInstance

    func createSingleTenantHsmInstance(
      request: CreateSingleTenantHsmInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createSingleTenantHsmInstanceProposal(
      request: CreateSingleTenantHsmInstanceProposalRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func approveSingleTenantHsmInstanceProposal(
      request: ApproveSingleTenantHsmInstanceProposalRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ApproveSingleTenantHsmInstanceProposalResponse

    func executeSingleTenantHsmInstanceProposal(
      request: ExecuteSingleTenantHsmInstanceProposalRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getSingleTenantHsmInstanceProposal(
      request: GetSingleTenantHsmInstanceProposalRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.SingleTenantHsmInstanceProposal

    func listSingleTenantHsmInstanceProposals(
      request: ListSingleTenantHsmInstanceProposalsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListSingleTenantHsmInstanceProposalsResponse

    func deleteSingleTenantHsmInstanceProposal(
      request: DeleteSingleTenantHsmInstanceProposalRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
