// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [KeyManagementService.ImportTrustedKeyWrappedCryptoKeyVersion][google.cloud.kms.v1.KeyManagementService.ImportTrustedKeyWrappedCryptoKeyVersion].
///
/// [google.cloud.kms.v1.KeyManagementService.ImportTrustedKeyWrappedCryptoKeyVersion]: <doc:KeyManagementServiceClient/importTrustedKeyWrappedCryptoKeyVersion(request:options:)>
public struct ImportTrustedKeyWrappedCryptoKeyVersionRequest: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The [name][google.cloud.kms.v1.CryptoKey.name] of the
  /// [CryptoKey][google.cloud.kms.v1.CryptoKey] to be imported into.
  ///
  /// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
  /// [google.cloud.kms.v1.CryptoKey.name]: <doc:CryptoKey/name>
  public var parent: Swift.String = Swift.String()

  /// Required. Required - the CKV of the trusted key used to import.
  /// This can be the name of a CryptoKeyVersion or a CryptoKey.
  public var importingKey: Swift.String = Swift.String()

  /// Optional. The optional [name][google.cloud.kms.v1.CryptoKeyVersion.name] of
  /// an existing [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] to
  /// target for an import operation. If this field is not present, a new
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] containing the
  /// supplied key material is created.
  ///
  /// If this field is present, the supplied key material is imported into
  /// the existing [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion]. To
  /// import into an existing
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion], the
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] must be a child of
  /// [ImportTrustedKeyWrappedCryptoKeyVersionRequest.parent][google.cloud.kms.v1.ImportTrustedKeyWrappedCryptoKeyVersionRequest.parent],
  /// have been previously created via
  /// [ImportTrustedKeyWrappedCryptoKeyVersion][google.cloud.kms.v1.KeyManagementService.ImportTrustedKeyWrappedCryptoKeyVersion],
  /// and be in
  /// [DESTROYED][google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState.DESTROYED]
  /// or
  /// [IMPORT_FAILED][google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState.IMPORT_FAILED]
  /// state. The key material and algorithm must match the previous
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] exactly if the
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] has ever contained
  /// key material
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  /// [google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState.DESTROYED]: <doc:CryptoKeyVersion/CryptoKeyVersionState/destroyed>
  /// [google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState.IMPORT_FAILED]: <doc:CryptoKeyVersion/CryptoKeyVersionState/importFailed>
  /// [google.cloud.kms.v1.CryptoKeyVersion.name]: <doc:CryptoKeyVersion/name>
  /// [google.cloud.kms.v1.ImportTrustedKeyWrappedCryptoKeyVersionRequest.parent]: <doc:ImportTrustedKeyWrappedCryptoKeyVersionRequest/parent>
  /// [google.cloud.kms.v1.KeyManagementService.ImportTrustedKeyWrappedCryptoKeyVersion]: <doc:KeyManagementServiceClient/importTrustedKeyWrappedCryptoKeyVersion(request:options:)>
  public var cryptoKeyVersion: Swift.String = Swift.String()

  /// Required. The target key pre-wrapped on premises.
  public var wrappedKey: Foundation.Data = Foundation.Data()

  /// Required. Required - The
  /// [algorithm][google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionAlgorithm]
  /// of the key being imported. This does not need to match the
  /// [version_template][google.cloud.kms.v1.CryptoKey.version_template] of the
  /// [CryptoKey][google.cloud.kms.v1.CryptoKey] this version imports into.
  ///
  /// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
  /// [google.cloud.kms.v1.CryptoKey.version_template]: <doc:CryptoKey/versionTemplate>
  /// [google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionAlgorithm]: <doc:CryptoKeyVersion/CryptoKeyVersionAlgorithm>
  public var algorithm: CryptoKeyVersion.CryptoKeyVersionAlgorithm =
    CryptoKeyVersion.CryptoKeyVersionAlgorithm()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImportTrustedKeyWrappedCryptoKeyVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportTrustedKeyWrappedCryptoKeyVersionRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let importingKey = CodingKeys(stringValue: "importingKey")
    static let cryptoKeyVersion = CodingKeys(stringValue: "cryptoKeyVersion")
    static let wrappedKey = CodingKeys(stringValue: "wrappedKey")
    static let algorithm = CodingKeys(stringValue: "algorithm")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "importingKey",
      "cryptoKeyVersion",
      "wrappedKey",
      "algorithm",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .importingKey) {
      self.importingKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cryptoKeyVersion) {
      self.cryptoKeyVersion = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .wrappedKey) {
      self.wrappedKey = value
    }
    if let value = try container.decodeIfPresent(
      CryptoKeyVersion.CryptoKeyVersionAlgorithm.self, forKey: .algorithm)
    {
      self.algorithm = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.importingKey, forKey: .importingKey)
    try container.encode(self.cryptoKeyVersion, forKey: .cryptoKeyVersion)
    try container.encode(self.wrappedKey, forKey: .wrappedKey)
    try container.encode(self.algorithm, forKey: .algorithm)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.ImportTrustedKeyWrappedCryptoKeyVersionRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
