// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Resource-oriented representation of a request to Cloud KMS Autokey and the
/// resulting provisioning of a [CryptoKey][google.cloud.kms.v1.CryptoKey].
///
/// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
public struct KeyHandle: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the [KeyHandle][google.cloud.kms.v1.KeyHandle]
  /// resource, e.g.
  /// `projects/{PROJECT_ID}/locations/{LOCATION}/keyHandles/{KEY_HANDLE_ID}`.
  ///
  /// [google.cloud.kms.v1.KeyHandle]: <doc:KeyHandle>
  public var name: Swift.String = Swift.String()

  /// Output only. Name of a [CryptoKey][google.cloud.kms.v1.CryptoKey] that has
  /// been provisioned for Customer Managed Encryption Key (CMEK) use in the
  /// [KeyHandle][google.cloud.kms.v1.KeyHandle] project and location for the
  /// requested resource type. The [CryptoKey][google.cloud.kms.v1.CryptoKey]
  /// project will reflect the value configured in the
  /// [AutokeyConfig][google.cloud.kms.v1.AutokeyConfig] on the resource
  /// project's ancestor folder at the time of the
  /// [KeyHandle][google.cloud.kms.v1.KeyHandle] creation. If more than one
  /// ancestor folder has a configured
  /// [AutokeyConfig][google.cloud.kms.v1.AutokeyConfig], the nearest of these
  /// configurations is used.
  ///
  /// [google.cloud.kms.v1.AutokeyConfig]: <doc:AutokeyConfig>
  /// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
  /// [google.cloud.kms.v1.KeyHandle]: <doc:KeyHandle>
  public var kmsKey: Swift.String = Swift.String()

  /// Required. Indicates the resource type that the resulting
  /// [CryptoKey][google.cloud.kms.v1.CryptoKey] is meant to protect, e.g.
  /// `{SERVICE}.googleapis.com/{TYPE}`. See documentation for supported resource
  /// types.
  ///
  /// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
  public var resourceTypeSelector: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `KeyHandle`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = KeyHandle().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let resourceTypeSelector = CodingKeys(stringValue: "resourceTypeSelector")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "kmsKey",
      "resourceTypeSelector",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
      self.kmsKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceTypeSelector) {
      self.resourceTypeSelector = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    try container.encode(self.resourceTypeSelector, forKey: .resourceTypeSelector)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.KeyHandle"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
