// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol KeyManagementServiceStub: Sendable {
    func listKeyRings(
      request: ListKeyRingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListKeyRingsResponse

    func listCryptoKeys(
      request: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListCryptoKeysResponse

    func listCryptoKeyVersions(
      request: ListCryptoKeyVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListCryptoKeyVersionsResponse

    func listImportJobs(
      request: ListImportJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListImportJobsResponse

    func listRetiredResources(
      request: ListRetiredResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListRetiredResourcesResponse

    func getKeyRing(
      request: GetKeyRingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.KeyRing

    func getCryptoKey(
      request: GetCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey

    func getCryptoKeyVersion(
      request: GetCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion

    func getPublicKey(
      request: GetPublicKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.PublicKey

    func getImportJob(
      request: GetImportJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ImportJob

    func getRetiredResource(
      request: GetRetiredResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.RetiredResource

    func createKeyRing(
      request: CreateKeyRingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.KeyRing

    func createCryptoKey(
      request: CreateCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey

    func createCryptoKeyVersion(
      request: CreateCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion

    func deleteCryptoKey(
      request: DeleteCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCryptoKeyVersion(
      request: DeleteCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func importCryptoKeyVersion(
      request: ImportCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion

    func importTrustedKeyWrappedCryptoKeyVersion(
      request: ImportTrustedKeyWrappedCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion

    func exportTrustedKeyWrappedCryptoKeyVersion(
      request: ExportTrustedKeyWrappedCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ExportTrustedKeyWrappedCryptoKeyVersionResponse

    func createImportJob(
      request: CreateImportJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ImportJob

    func updateCryptoKey(
      request: UpdateCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey

    func updateCryptoKeyVersion(
      request: UpdateCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion

    func updateCryptoKeyPrimaryVersion(
      request: UpdateCryptoKeyPrimaryVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey

    func destroyCryptoKeyVersion(
      request: DestroyCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion

    func restoreCryptoKeyVersion(
      request: RestoreCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion

    func encrypt(
      request: EncryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.EncryptResponse

    func decrypt(
      request: DecryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.DecryptResponse

    func rawEncrypt(
      request: RawEncryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.RawEncryptResponse

    func rawDecrypt(
      request: RawDecryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.RawDecryptResponse

    func asymmetricSign(
      request: AsymmetricSignRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.AsymmetricSignResponse

    func asymmetricDecrypt(
      request: AsymmetricDecryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.AsymmetricDecryptResponse

    func macSign(
      request: MacSignRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.MacSignResponse

    func macVerify(
      request: MacVerifyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.MacVerifyResponse

    func decapsulate(
      request: DecapsulateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.DecapsulateResponse

    func generateRandomBytes(
      request: GenerateRandomBytesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.GenerateRandomBytesResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
