// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class KeyManagementServiceLogging: KeyManagementServiceStub {
    let inner: any KeyManagementServiceStub
    let logger: Logger

    public init(_ inner: any KeyManagementServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-kms-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudkms"
      logger[metadataKey: "gcp.experimental.swift.client"] = "KeyManagementService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listKeyRings(
      request: ListKeyRingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListKeyRingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listKeyRings",
        action: {
          (r: ListKeyRingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ListKeyRingsResponse
          in
          return try await self.inner.listKeyRings(request: r, options: o)
        })
    }

    public func listCryptoKeys(
      request: ListCryptoKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListCryptoKeysResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCryptoKeys",
        action: {
          (r: ListCryptoKeysRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ListCryptoKeysResponse
          in
          return try await self.inner.listCryptoKeys(request: r, options: o)
        })
    }

    public func listCryptoKeyVersions(
      request: ListCryptoKeyVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListCryptoKeyVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCryptoKeyVersions",
        action: {
          (r: ListCryptoKeyVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ListCryptoKeyVersionsResponse
          in
          return try await self.inner.listCryptoKeyVersions(request: r, options: o)
        })
    }

    public func listImportJobs(
      request: ListImportJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListImportJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listImportJobs",
        action: {
          (r: ListImportJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ListImportJobsResponse
          in
          return try await self.inner.listImportJobs(request: r, options: o)
        })
    }

    public func listRetiredResources(
      request: ListRetiredResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ListRetiredResourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRetiredResources",
        action: {
          (r: ListRetiredResourcesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ListRetiredResourcesResponse
          in
          return try await self.inner.listRetiredResources(request: r, options: o)
        })
    }

    public func getKeyRing(
      request: GetKeyRingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.KeyRing {
      try await self._intercept(
        request: request,
        options: options,
        name: "getKeyRing",
        action: {
          (r: GetKeyRingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.KeyRing
          in
          return try await self.inner.getKeyRing(request: r, options: o)
        })
    }

    public func getCryptoKey(
      request: GetCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCryptoKey",
        action: {
          (r: GetCryptoKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKey
          in
          return try await self.inner.getCryptoKey(request: r, options: o)
        })
    }

    public func getCryptoKeyVersion(
      request: GetCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCryptoKeyVersion",
        action: {
          (r: GetCryptoKeyVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKeyVersion
          in
          return try await self.inner.getCryptoKeyVersion(request: r, options: o)
        })
    }

    public func getPublicKey(
      request: GetPublicKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.PublicKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPublicKey",
        action: {
          (r: GetPublicKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.PublicKey
          in
          return try await self.inner.getPublicKey(request: r, options: o)
        })
    }

    public func getImportJob(
      request: GetImportJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ImportJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getImportJob",
        action: {
          (r: GetImportJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ImportJob
          in
          return try await self.inner.getImportJob(request: r, options: o)
        })
    }

    public func getRetiredResource(
      request: GetRetiredResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.RetiredResource {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRetiredResource",
        action: {
          (r: GetRetiredResourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.RetiredResource
          in
          return try await self.inner.getRetiredResource(request: r, options: o)
        })
    }

    public func createKeyRing(
      request: CreateKeyRingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.KeyRing {
      try await self._intercept(
        request: request,
        options: options,
        name: "createKeyRing",
        action: {
          (r: CreateKeyRingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.KeyRing
          in
          return try await self.inner.createKeyRing(request: r, options: o)
        })
    }

    public func createCryptoKey(
      request: CreateCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCryptoKey",
        action: {
          (r: CreateCryptoKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKey
          in
          return try await self.inner.createCryptoKey(request: r, options: o)
        })
    }

    public func createCryptoKeyVersion(
      request: CreateCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCryptoKeyVersion",
        action: {
          (r: CreateCryptoKeyVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKeyVersion
          in
          return try await self.inner.createCryptoKeyVersion(request: r, options: o)
        })
    }

    public func deleteCryptoKey(
      request: DeleteCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCryptoKey",
        action: {
          (r: DeleteCryptoKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCryptoKey(request: r, options: o)
        })
    }

    public func deleteCryptoKeyVersion(
      request: DeleteCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCryptoKeyVersion",
        action: {
          (r: DeleteCryptoKeyVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCryptoKeyVersion(request: r, options: o)
        })
    }

    public func importCryptoKeyVersion(
      request: ImportCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "importCryptoKeyVersion",
        action: {
          (r: ImportCryptoKeyVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKeyVersion
          in
          return try await self.inner.importCryptoKeyVersion(request: r, options: o)
        })
    }

    public func importTrustedKeyWrappedCryptoKeyVersion(
      request: ImportTrustedKeyWrappedCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "importTrustedKeyWrappedCryptoKeyVersion",
        action: {
          (r: ImportTrustedKeyWrappedCryptoKeyVersionRequest, o: GoogleGax.RequestOptions)
            async throws -> GoogleCloudKMSV1.CryptoKeyVersion
          in
          return try await self.inner.importTrustedKeyWrappedCryptoKeyVersion(
            request: r, options: o)
        })
    }

    public func exportTrustedKeyWrappedCryptoKeyVersion(
      request: ExportTrustedKeyWrappedCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ExportTrustedKeyWrappedCryptoKeyVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportTrustedKeyWrappedCryptoKeyVersion",
        action: {
          (r: ExportTrustedKeyWrappedCryptoKeyVersionRequest, o: GoogleGax.RequestOptions)
            async throws -> GoogleCloudKMSV1.ExportTrustedKeyWrappedCryptoKeyVersionResponse
          in
          return try await self.inner.exportTrustedKeyWrappedCryptoKeyVersion(
            request: r, options: o)
        })
    }

    public func createImportJob(
      request: CreateImportJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.ImportJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "createImportJob",
        action: {
          (r: CreateImportJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.ImportJob
          in
          return try await self.inner.createImportJob(request: r, options: o)
        })
    }

    public func updateCryptoKey(
      request: UpdateCryptoKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCryptoKey",
        action: {
          (r: UpdateCryptoKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKey
          in
          return try await self.inner.updateCryptoKey(request: r, options: o)
        })
    }

    public func updateCryptoKeyVersion(
      request: UpdateCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCryptoKeyVersion",
        action: {
          (r: UpdateCryptoKeyVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKeyVersion
          in
          return try await self.inner.updateCryptoKeyVersion(request: r, options: o)
        })
    }

    public func updateCryptoKeyPrimaryVersion(
      request: UpdateCryptoKeyPrimaryVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCryptoKeyPrimaryVersion",
        action: {
          (r: UpdateCryptoKeyPrimaryVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKey
          in
          return try await self.inner.updateCryptoKeyPrimaryVersion(request: r, options: o)
        })
    }

    public func destroyCryptoKeyVersion(
      request: DestroyCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "destroyCryptoKeyVersion",
        action: {
          (r: DestroyCryptoKeyVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKeyVersion
          in
          return try await self.inner.destroyCryptoKeyVersion(request: r, options: o)
        })
    }

    public func restoreCryptoKeyVersion(
      request: RestoreCryptoKeyVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.CryptoKeyVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "restoreCryptoKeyVersion",
        action: {
          (r: RestoreCryptoKeyVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.CryptoKeyVersion
          in
          return try await self.inner.restoreCryptoKeyVersion(request: r, options: o)
        })
    }

    public func encrypt(
      request: EncryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.EncryptResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "encrypt",
        action: {
          (r: EncryptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.EncryptResponse
          in
          return try await self.inner.encrypt(request: r, options: o)
        })
    }

    public func decrypt(
      request: DecryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.DecryptResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "decrypt",
        action: {
          (r: DecryptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.DecryptResponse
          in
          return try await self.inner.decrypt(request: r, options: o)
        })
    }

    public func rawEncrypt(
      request: RawEncryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.RawEncryptResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "rawEncrypt",
        action: {
          (r: RawEncryptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.RawEncryptResponse
          in
          return try await self.inner.rawEncrypt(request: r, options: o)
        })
    }

    public func rawDecrypt(
      request: RawDecryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.RawDecryptResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "rawDecrypt",
        action: {
          (r: RawDecryptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.RawDecryptResponse
          in
          return try await self.inner.rawDecrypt(request: r, options: o)
        })
    }

    public func asymmetricSign(
      request: AsymmetricSignRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.AsymmetricSignResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "asymmetricSign",
        action: {
          (r: AsymmetricSignRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.AsymmetricSignResponse
          in
          return try await self.inner.asymmetricSign(request: r, options: o)
        })
    }

    public func asymmetricDecrypt(
      request: AsymmetricDecryptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.AsymmetricDecryptResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "asymmetricDecrypt",
        action: {
          (r: AsymmetricDecryptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.AsymmetricDecryptResponse
          in
          return try await self.inner.asymmetricDecrypt(request: r, options: o)
        })
    }

    public func macSign(
      request: MacSignRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.MacSignResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "macSign",
        action: {
          (r: MacSignRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.MacSignResponse
          in
          return try await self.inner.macSign(request: r, options: o)
        })
    }

    public func macVerify(
      request: MacVerifyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.MacVerifyResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "macVerify",
        action: {
          (r: MacVerifyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.MacVerifyResponse
          in
          return try await self.inner.macVerify(request: r, options: o)
        })
    }

    public func decapsulate(
      request: DecapsulateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.DecapsulateResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "decapsulate",
        action: {
          (r: DecapsulateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.DecapsulateResponse
          in
          return try await self.inner.decapsulate(request: r, options: o)
        })
    }

    public func generateRandomBytes(
      request: GenerateRandomBytesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudKMSV1.GenerateRandomBytesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateRandomBytes",
        action: {
          (r: GenerateRandomBytesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudKMSV1.GenerateRandomBytesResponse
          in
          return try await self.inner.generateRandomBytes(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
