// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [KeyManagementService.ListCryptoKeyVersions][google.cloud.kms.v1.KeyManagementService.ListCryptoKeyVersions].
///
/// [google.cloud.kms.v1.KeyManagementService.ListCryptoKeyVersions]: <doc:KeyManagementServiceClient/listCryptoKeyVersions(request:options:)>
public struct ListCryptoKeyVersionsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The list of [CryptoKeyVersions][google.cloud.kms.v1.CryptoKeyVersion].
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  public var cryptoKeyVersions: [CryptoKeyVersion] = []

  /// A token to retrieve next page of results. Pass this value in
  /// [ListCryptoKeyVersionsRequest.page_token][google.cloud.kms.v1.ListCryptoKeyVersionsRequest.page_token]
  /// to retrieve the next page of results.
  ///
  /// [google.cloud.kms.v1.ListCryptoKeyVersionsRequest.page_token]: <doc:ListCryptoKeyVersionsRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// The total number of
  /// [CryptoKeyVersions][google.cloud.kms.v1.CryptoKeyVersion] that matched the
  /// query.
  ///
  /// This field is not populated if
  /// [ListCryptoKeyVersionsRequest.filter][google.cloud.kms.v1.ListCryptoKeyVersionsRequest.filter]
  /// is applied.
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  /// [google.cloud.kms.v1.ListCryptoKeyVersionsRequest.filter]: <doc:ListCryptoKeyVersionsRequest/filter>
  public var totalSize: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListCryptoKeyVersionsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCryptoKeyVersionsResponse().with { $0.cryptoKeyVersions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cryptoKeyVersions = CodingKeys(stringValue: "cryptoKeyVersions")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let totalSize = CodingKeys(stringValue: "totalSize")

    static let _knownKeys: Set<Swift.String> = [
      "cryptoKeyVersions",
      "nextPageToken",
      "totalSize",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [CryptoKeyVersion].self, forKey: .cryptoKeyVersions)
    {
      self.cryptoKeyVersions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cryptoKeyVersions, forKey: .cryptoKeyVersions)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.totalSize, forKey: .totalSize)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.ListCryptoKeyVersionsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [CryptoKeyVersion] {
    return self.cryptoKeyVersions
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
