// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleGax
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response message for
/// [HsmManagement.ListSingleTenantHsmInstanceProposals][google.cloud.kms.v1.HsmManagement.ListSingleTenantHsmInstanceProposals].
///
/// [google.cloud.kms.v1.HsmManagement.ListSingleTenantHsmInstanceProposals]: <doc:HsmManagementClient/listSingleTenantHsmInstanceProposals(request:options:)>
public struct ListSingleTenantHsmInstanceProposalsResponse: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  Sendable
{
  /// The list of
  /// [SingleTenantHsmInstanceProposals][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var singleTenantHsmInstanceProposals: [SingleTenantHsmInstanceProposal] = []

  /// A token to retrieve next page of results. Pass this value in
  /// [ListSingleTenantHsmInstanceProposalsRequest.page_token][google.cloud.kms.v1.ListSingleTenantHsmInstanceProposalsRequest.page_token]
  /// to retrieve the next page of results.
  ///
  /// [google.cloud.kms.v1.ListSingleTenantHsmInstanceProposalsRequest.page_token]: <doc:ListSingleTenantHsmInstanceProposalsRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// The total number of
  /// [SingleTenantHsmInstanceProposals][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
  /// that matched the query.
  ///
  /// This field is not populated if
  /// [ListSingleTenantHsmInstanceProposalsRequest.filter][google.cloud.kms.v1.ListSingleTenantHsmInstanceProposalsRequest.filter]
  /// is applied.
  ///
  /// [google.cloud.kms.v1.ListSingleTenantHsmInstanceProposalsRequest.filter]: <doc:ListSingleTenantHsmInstanceProposalsRequest/filter>
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var totalSize: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListSingleTenantHsmInstanceProposalsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListSingleTenantHsmInstanceProposalsResponse().with { $0.singleTenantHsmInstanceProposals = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let singleTenantHsmInstanceProposals = CodingKeys(
      stringValue: "singleTenantHsmInstanceProposals")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let totalSize = CodingKeys(stringValue: "totalSize")

    static let _knownKeys: Set<Swift.String> = [
      "singleTenantHsmInstanceProposals",
      "nextPageToken",
      "totalSize",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [SingleTenantHsmInstanceProposal].self, forKey: .singleTenantHsmInstanceProposals)
    {
      self.singleTenantHsmInstanceProposals = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(
      self.singleTenantHsmInstanceProposals, forKey: .singleTenantHsmInstanceProposals)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.totalSize, forKey: .totalSize)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.ListSingleTenantHsmInstanceProposalsResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListSingleTenantHsmInstanceProposalsResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [SingleTenantHsmInstanceProposal] {
    return self.singleTenantHsmInstanceProposals
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
