// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for
/// [KeyManagementService.ListKeyRings][google.cloud.kms.v1.KeyManagementService.ListKeyRings].
///
/// [google.cloud.kms.v1.KeyManagementService.ListKeyRings]: <doc:KeyManagementServiceClient/listKeyRings(request:options:)>
public struct ListKeyRingsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of [KeyRings][google.cloud.kms.v1.KeyRing].
  ///
  /// [google.cloud.kms.v1.KeyRing]: <doc:KeyRing>
  public var keyRings: [KeyRing] = []

  /// A token to retrieve next page of results. Pass this value in
  /// [ListKeyRingsRequest.page_token][google.cloud.kms.v1.ListKeyRingsRequest.page_token]
  /// to retrieve the next page of results.
  ///
  /// [google.cloud.kms.v1.ListKeyRingsRequest.page_token]: <doc:ListKeyRingsRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// The total number of [KeyRings][google.cloud.kms.v1.KeyRing] that matched
  /// the query.
  ///
  /// This field is not populated if
  /// [ListKeyRingsRequest.filter][google.cloud.kms.v1.ListKeyRingsRequest.filter]
  /// is applied.
  ///
  /// [google.cloud.kms.v1.KeyRing]: <doc:KeyRing>
  /// [google.cloud.kms.v1.ListKeyRingsRequest.filter]: <doc:ListKeyRingsRequest/filter>
  public var totalSize: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListKeyRingsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListKeyRingsResponse().with { $0.keyRings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let keyRings = CodingKeys(stringValue: "keyRings")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let totalSize = CodingKeys(stringValue: "totalSize")

    static let _knownKeys: Set<Swift.String> = [
      "keyRings",
      "nextPageToken",
      "totalSize",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([KeyRing].self, forKey: .keyRings) {
      self.keyRings = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.keyRings, forKey: .keyRings)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.totalSize, forKey: .totalSize)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.ListKeyRingsResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListKeyRingsResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [KeyRing] {
    return self.keyRings
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
