// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [KeyManagementService.MacVerify][google.cloud.kms.v1.KeyManagementService.MacVerify].
///
/// [google.cloud.kms.v1.KeyManagementService.MacVerify]: <doc:KeyManagementServiceClient/macVerify(request:options:)>
public struct MacVerifyRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] to use for
  /// verification.
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  public var name: Swift.String = Swift.String()

  /// Required. The data used previously as a
  /// [MacSignRequest.data][google.cloud.kms.v1.MacSignRequest.data] to generate
  /// the MAC tag.
  ///
  /// [google.cloud.kms.v1.MacSignRequest.data]: <doc:MacSignRequest/data>
  public var data: Foundation.Data = Foundation.Data()

  /// Optional. An optional CRC32C checksum of the
  /// [MacVerifyRequest.data][google.cloud.kms.v1.MacVerifyRequest.data]. If
  /// specified, [KeyManagementService][google.cloud.kms.v1.KeyManagementService]
  /// will verify the integrity of the received
  /// [MacVerifyRequest.data][google.cloud.kms.v1.MacVerifyRequest.data] using
  /// this checksum.
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// report an error if the checksum verification fails. If you receive a
  /// checksum error, your client should verify that
  /// CRC32C([MacVerifyRequest.data][google.cloud.kms.v1.MacVerifyRequest.data])
  /// is equal to
  /// [MacVerifyRequest.data_crc32c][google.cloud.kms.v1.MacVerifyRequest.data_crc32c],
  /// and if so, perform a limited number of retries. A persistent mismatch may
  /// indicate an issue in your computation of the CRC32C checksum. Note: This
  /// field is defined as int64 for reasons of compatibility across different
  /// languages. However, it is a non-negative integer, which will never exceed
  /// 2^32-1, and can be safely downconverted to uint32 in languages that support
  /// this type.
  ///
  /// [google.cloud.kms.v1.KeyManagementService]: <doc:KeyManagementServiceClient>
  /// [google.cloud.kms.v1.MacVerifyRequest.data]: <doc:MacVerifyRequest/data>
  /// [google.cloud.kms.v1.MacVerifyRequest.data_crc32c]: <doc:MacVerifyRequest/dataCrc32C>
  public var dataCrc32C: GoogleCloudWKT.Int64Value? = nil

  /// Required. The signature to verify.
  public var mac: Foundation.Data = Foundation.Data()

  /// Optional. An optional CRC32C checksum of the
  /// [MacVerifyRequest.mac][google.cloud.kms.v1.MacVerifyRequest.mac]. If
  /// specified, [KeyManagementService][google.cloud.kms.v1.KeyManagementService]
  /// will verify the integrity of the received
  /// [MacVerifyRequest.mac][google.cloud.kms.v1.MacVerifyRequest.mac] using this
  /// checksum. [KeyManagementService][google.cloud.kms.v1.KeyManagementService]
  /// will report an error if the checksum verification fails. If you receive a
  /// checksum error, your client should verify that
  /// CRC32C([MacVerifyRequest.mac][google.cloud.kms.v1.MacVerifyRequest.mac]) is
  /// equal to
  /// [MacVerifyRequest.mac_crc32c][google.cloud.kms.v1.MacVerifyRequest.mac_crc32c],
  /// and if so, perform a limited number of retries. A persistent mismatch may
  /// indicate an issue in your computation of the CRC32C checksum. Note: This
  /// field is defined as int64 for reasons of compatibility across different
  /// languages. However, it is a non-negative integer, which will never exceed
  /// 2^32-1, and can be safely downconverted to uint32 in languages that support
  /// this type.
  ///
  /// [google.cloud.kms.v1.KeyManagementService]: <doc:KeyManagementServiceClient>
  /// [google.cloud.kms.v1.MacVerifyRequest.mac]: <doc:MacVerifyRequest/mac>
  /// [google.cloud.kms.v1.MacVerifyRequest.mac_crc32c]: <doc:MacVerifyRequest/macCrc32C>
  public var macCrc32C: GoogleCloudWKT.Int64Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `MacVerifyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MacVerifyRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let data = CodingKeys(stringValue: "data")
    static let dataCrc32C = CodingKeys(stringValue: "dataCrc32c")
    static let mac = CodingKeys(stringValue: "mac")
    static let macCrc32C = CodingKeys(stringValue: "macCrc32c")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "data",
      "dataCrc32c",
      "mac",
      "macCrc32c",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .data) {
      self.data = value
    }
    self.dataCrc32C = try container.decodeIfPresent(
      GoogleCloudWKT.Int64Value.self, forKey: .dataCrc32C)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .mac) {
      self.mac = value
    }
    self.macCrc32C = try container.decodeIfPresent(
      GoogleCloudWKT.Int64Value.self, forKey: .macCrc32C)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.data, forKey: .data)
    try container.encodeIfPresent(self.dataCrc32C, forKey: .dataCrc32C)
    try container.encode(self.mac, forKey: .mac)
    try container.encodeIfPresent(self.macCrc32C, forKey: .macCrc32C)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.MacVerifyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
