// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [KeyManagementService.RawDecrypt][google.cloud.kms.v1.KeyManagementService.RawDecrypt].
///
/// [google.cloud.kms.v1.KeyManagementService.RawDecrypt]: <doc:KeyManagementServiceClient/rawDecrypt(request:options:)>
public struct RawDecryptRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] to use for
  /// decryption.
  ///
  /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
  public var name: Swift.String = Swift.String()

  /// Required. The encrypted data originally returned in
  /// [RawEncryptResponse.ciphertext][google.cloud.kms.v1.RawEncryptResponse.ciphertext].
  ///
  /// [google.cloud.kms.v1.RawEncryptResponse.ciphertext]: <doc:RawEncryptResponse/ciphertext>
  public var ciphertext: Foundation.Data = Foundation.Data()

  /// Optional. Optional data that must match the data originally supplied in
  /// [RawEncryptRequest.additional_authenticated_data][google.cloud.kms.v1.RawEncryptRequest.additional_authenticated_data].
  ///
  /// [google.cloud.kms.v1.RawEncryptRequest.additional_authenticated_data]: <doc:RawEncryptRequest/additionalAuthenticatedData>
  public var additionalAuthenticatedData: Foundation.Data = Foundation.Data()

  /// Required. The initialization vector (IV) used during encryption, which must
  /// match the data originally provided in
  /// [RawEncryptResponse.initialization_vector][google.cloud.kms.v1.RawEncryptResponse.initialization_vector].
  ///
  /// [google.cloud.kms.v1.RawEncryptResponse.initialization_vector]: <doc:RawEncryptResponse/initializationVector>
  public var initializationVector: Foundation.Data = Foundation.Data()

  /// The length of the authentication tag that is appended to the end of
  /// the ciphertext. If unspecified (0), the default value for the key's
  /// algorithm will be used (for AES-GCM, the default value is 16).
  public var tagLength: Swift.Int32 = Swift.Int32()

  /// Optional. An optional CRC32C checksum of the
  /// [RawDecryptRequest.ciphertext][google.cloud.kms.v1.RawDecryptRequest.ciphertext].
  /// If specified,
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// verify the integrity of the received ciphertext using this checksum.
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// report an error if the checksum verification fails. If you receive a
  /// checksum error, your client should verify that CRC32C(ciphertext) is equal
  /// to ciphertext_crc32c, and if so, perform a limited number of retries. A
  /// persistent mismatch may indicate an issue in your computation of the CRC32C
  /// checksum. Note: This field is defined as int64 for reasons of compatibility
  /// across different languages. However, it is a non-negative integer, which
  /// will never exceed 2^32-1, and can be safely downconverted to uint32 in
  /// languages that support this type.
  ///
  /// [google.cloud.kms.v1.KeyManagementService]: <doc:KeyManagementServiceClient>
  /// [google.cloud.kms.v1.RawDecryptRequest.ciphertext]: <doc:RawDecryptRequest/ciphertext>
  public var ciphertextCrc32C: GoogleWKT.WKTInt64Value? = nil

  /// Optional. An optional CRC32C checksum of the
  /// [RawDecryptRequest.additional_authenticated_data][google.cloud.kms.v1.RawDecryptRequest.additional_authenticated_data].
  /// If specified,
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// verify the integrity of the received additional_authenticated_data using
  /// this checksum.
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// report an error if the checksum verification fails. If you receive a
  /// checksum error, your client should verify that
  /// CRC32C(additional_authenticated_data) is equal to
  /// additional_authenticated_data_crc32c, and if so, perform
  /// a limited number of retries. A persistent mismatch may indicate an issue in
  /// your computation of the CRC32C checksum.
  /// Note: This field is defined as int64 for reasons of compatibility across
  /// different languages. However, it is a non-negative integer, which will
  /// never exceed 2^32-1, and can be safely downconverted to uint32 in languages
  /// that support this type.
  ///
  /// [google.cloud.kms.v1.KeyManagementService]: <doc:KeyManagementServiceClient>
  /// [google.cloud.kms.v1.RawDecryptRequest.additional_authenticated_data]: <doc:RawDecryptRequest/additionalAuthenticatedData>
  public var additionalAuthenticatedDataCrc32C: GoogleWKT.WKTInt64Value? = nil

  /// Optional. An optional CRC32C checksum of the
  /// [RawDecryptRequest.initialization_vector][google.cloud.kms.v1.RawDecryptRequest.initialization_vector].
  /// If specified,
  /// [KeyManagementService][google.cloud.kms.v1.KeyManagementService] will
  /// verify the integrity of the received initialization_vector using this
  /// checksum. [KeyManagementService][google.cloud.kms.v1.KeyManagementService]
  /// will report an error if the checksum verification fails. If you receive a
  /// checksum error, your client should verify that
  /// CRC32C(initialization_vector) is equal to initialization_vector_crc32c, and
  /// if so, perform a limited number of retries. A persistent mismatch may
  /// indicate an issue in your computation of the CRC32C checksum.
  /// Note: This field is defined as int64 for reasons of compatibility across
  /// different languages. However, it is a non-negative integer, which will
  /// never exceed 2^32-1, and can be safely downconverted to uint32 in languages
  /// that support this type.
  ///
  /// [google.cloud.kms.v1.KeyManagementService]: <doc:KeyManagementServiceClient>
  /// [google.cloud.kms.v1.RawDecryptRequest.initialization_vector]: <doc:RawDecryptRequest/initializationVector>
  public var initializationVectorCrc32C: GoogleWKT.WKTInt64Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RawDecryptRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RawDecryptRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let ciphertext = CodingKeys(stringValue: "ciphertext")
    static let additionalAuthenticatedData = CodingKeys(stringValue: "additionalAuthenticatedData")
    static let initializationVector = CodingKeys(stringValue: "initializationVector")
    static let tagLength = CodingKeys(stringValue: "tagLength")
    static let ciphertextCrc32C = CodingKeys(stringValue: "ciphertextCrc32c")
    static let additionalAuthenticatedDataCrc32C = CodingKeys(
      stringValue: "additionalAuthenticatedDataCrc32c")
    static let initializationVectorCrc32C = CodingKeys(stringValue: "initializationVectorCrc32c")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "ciphertext",
      "additionalAuthenticatedData",
      "initializationVector",
      "tagLength",
      "ciphertextCrc32c",
      "additionalAuthenticatedDataCrc32c",
      "initializationVectorCrc32c",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .ciphertext) {
      self.ciphertext = value
    }
    if let value = try container.decodeIfPresent(
      Foundation.Data.self, forKey: .additionalAuthenticatedData)
    {
      self.additionalAuthenticatedData = value
    }
    if let value = try container.decodeIfPresent(
      Foundation.Data.self, forKey: .initializationVector)
    {
      self.initializationVector = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .tagLength) {
      self.tagLength = value
    }
    self.ciphertextCrc32C = try container.decodeIfPresent(
      GoogleWKT.WKTInt64Value.self, forKey: .ciphertextCrc32C)
    self.additionalAuthenticatedDataCrc32C = try container.decodeIfPresent(
      GoogleWKT.WKTInt64Value.self, forKey: .additionalAuthenticatedDataCrc32C)
    self.initializationVectorCrc32C = try container.decodeIfPresent(
      GoogleWKT.WKTInt64Value.self, forKey: .initializationVectorCrc32C)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.ciphertext, forKey: .ciphertext)
    try container.encode(self.additionalAuthenticatedData, forKey: .additionalAuthenticatedData)
    try container.encode(self.initializationVector, forKey: .initializationVector)
    try container.encode(self.tagLength, forKey: .tagLength)
    try container.encodeIfPresent(self.ciphertextCrc32C, forKey: .ciphertextCrc32C)
    try container.encodeIfPresent(
      self.additionalAuthenticatedDataCrc32C, forKey: .additionalAuthenticatedDataCrc32C)
    try container.encodeIfPresent(
      self.initializationVectorCrc32C, forKey: .initializationVectorCrc32C)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.RawDecryptRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
