// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A RetiredResource resource represents the record of a deleted
/// [CryptoKey][google.cloud.kms.v1.CryptoKey]. Its purpose is to provide
/// visibility into retained user data and to prevent reuse of these names for
/// new [CryptoKeys][google.cloud.kms.v1.CryptoKey].
///
/// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
public struct RetiredResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name for this
  /// [RetiredResource][google.cloud.kms.v1.RetiredResource] in the format
  /// `projects/*/locations/*/retiredResources/*`.
  ///
  /// [google.cloud.kms.v1.RetiredResource]: <doc:RetiredResource>
  public var name: Swift.String = Swift.String()

  /// Output only. The full resource name of the original
  /// [CryptoKey][google.cloud.kms.v1.CryptoKey] that was deleted in the format
  /// `projects/*/locations/*/keyRings/*/cryptoKeys/*`.
  ///
  /// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
  public var originalResource: Swift.String = Swift.String()

  /// Output only. The resource type of the original deleted resource.
  public var resourceType: Swift.String = Swift.String()

  /// Output only. The time at which the original resource was deleted and this
  /// RetiredResource record was created.
  public var deleteTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `RetiredResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RetiredResource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let originalResource = CodingKeys(stringValue: "originalResource")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "originalResource",
      "resourceType",
      "deleteTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .originalResource) {
      self.originalResource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    self.deleteTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .deleteTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.originalResource, forKey: .originalResource)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.RetiredResource"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
