// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A
/// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
/// represents a proposal to perform an operation on a
/// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
///
/// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
/// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
public struct SingleTenantHsmInstanceProposal: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for this
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] in
  /// the format `projects/*/locations/*/singleTenantHsmInstances/*/proposals/*`.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
  /// was created.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The state of the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var state: SingleTenantHsmInstanceProposal.State = SingleTenantHsmInstanceProposal.State()

  /// Output only. The root cause of the most recent failure. Only present if
  /// [state][google.cloud.kms.v1.SingleTenantHsmInstanceProposal.state] is
  /// [FAILED][SingleTenantHsmInstanceProposal.FAILED].
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal.state]: <doc:SingleTenantHsmInstanceProposal/state>
  public var failureReason: Swift.String = Swift.String()

  /// Output only. The time at which the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
  /// was deleted.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the soft-deleted
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
  /// will be permanently purged. This field is only populated
  /// when the state is DELETED and will be set a time after expiration of the
  /// proposal, i.e. >= expire_time or (create_time + ttl).
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var purgeTime: GoogleWKT.WKTTimestamp? = nil

  /// The approval parameters for the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  /// The type of parameters is determined by the operation being proposed.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var approvalParameters: ApprovalParametersOneOf? = nil

  /// The expiration of the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  /// If not set, the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
  /// will expire in 1 day. The maximum expire time is 7 days. The minimum expire
  /// time is 5 minutes.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public var expiration: ExpirationOneOf? = nil

  /// The operation to perform on the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  public var operation: OperationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SingleTenantHsmInstanceProposal`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SingleTenantHsmInstanceProposal().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let state = CodingKeys(stringValue: "state")
    static let failureReason = CodingKeys(stringValue: "failureReason")
    static let quorumParameters = CodingKeys(stringValue: "quorumParameters")
    static let requiredActionQuorumParameters = CodingKeys(
      stringValue: "requiredActionQuorumParameters")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let ttl = CodingKeys(stringValue: "ttl")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let purgeTime = CodingKeys(stringValue: "purgeTime")
    static let registerTwoFactorAuthKeys = CodingKeys(stringValue: "registerTwoFactorAuthKeys")
    static let disableSingleTenantHsmInstance = CodingKeys(
      stringValue: "disableSingleTenantHsmInstance")
    static let enableSingleTenantHsmInstance = CodingKeys(
      stringValue: "enableSingleTenantHsmInstance")
    static let deleteSingleTenantHsmInstance = CodingKeys(
      stringValue: "deleteSingleTenantHsmInstance")
    static let addQuorumMember = CodingKeys(stringValue: "addQuorumMember")
    static let removeQuorumMember = CodingKeys(stringValue: "removeQuorumMember")
    static let refreshSingleTenantHsmInstance = CodingKeys(
      stringValue: "refreshSingleTenantHsmInstance")
    static let upgradeKeyTrust = CodingKeys(stringValue: "upgradeKeyTrust")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "state",
      "failureReason",
      "quorumParameters",
      "requiredActionQuorumParameters",
      "expireTime",
      "ttl",
      "deleteTime",
      "purgeTime",
      "registerTwoFactorAuthKeys",
      "disableSingleTenantHsmInstance",
      "enableSingleTenantHsmInstance",
      "deleteSingleTenantHsmInstance",
      "addQuorumMember",
      "removeQuorumMember",
      "refreshSingleTenantHsmInstance",
      "upgradeKeyTrust",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.State.self, forKey: .state)
    {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .failureReason) {
      self.failureReason = value
    }
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    self.purgeTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .purgeTime)

    var approvalParameters: ApprovalParametersOneOf? = nil
    let approvalParametersCheckAndSet = {
      if approvalParameters != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'approvalParameters'"))
      }
      approvalParameters = $0
    }
    if let quorumParameters = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.QuorumParameters?.self, forKey: .quorumParameters)
    {
      try approvalParametersCheckAndSet(.quorumParameters(quorumParameters))
    }
    if let requiredActionQuorumParameters = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters?.self,
      forKey: .requiredActionQuorumParameters)
    {
      try approvalParametersCheckAndSet(
        .requiredActionQuorumParameters(requiredActionQuorumParameters))
    }
    self.approvalParameters = approvalParameters

    var expiration: ExpirationOneOf? = nil
    let expirationCheckAndSet = {
      if expiration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'expiration'"))
      }
      expiration = $0
    }
    if let expireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp?.self, forKey: .expireTime)
    {
      try expirationCheckAndSet(.expireTime(expireTime))
    }
    if let ttl = try container.decodeIfPresent(GoogleWKT.WKTDuration?.self, forKey: .ttl) {
      try expirationCheckAndSet(.ttl(ttl))
    }
    self.expiration = expiration

    var operation: OperationOneOf? = nil
    let operationCheckAndSet = {
      if operation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'operation'"))
      }
      operation = $0
    }
    if let registerTwoFactorAuthKeys = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.RegisterTwoFactorAuthKeys?.self,
      forKey: .registerTwoFactorAuthKeys)
    {
      try operationCheckAndSet(.registerTwoFactorAuthKeys(registerTwoFactorAuthKeys))
    }
    if let disableSingleTenantHsmInstance = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.DisableSingleTenantHsmInstance?.self,
      forKey: .disableSingleTenantHsmInstance)
    {
      try operationCheckAndSet(.disableSingleTenantHsmInstance(disableSingleTenantHsmInstance))
    }
    if let enableSingleTenantHsmInstance = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.EnableSingleTenantHsmInstance?.self,
      forKey: .enableSingleTenantHsmInstance)
    {
      try operationCheckAndSet(.enableSingleTenantHsmInstance(enableSingleTenantHsmInstance))
    }
    if let deleteSingleTenantHsmInstance = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.DeleteSingleTenantHsmInstance?.self,
      forKey: .deleteSingleTenantHsmInstance)
    {
      try operationCheckAndSet(.deleteSingleTenantHsmInstance(deleteSingleTenantHsmInstance))
    }
    if let addQuorumMember = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.AddQuorumMember?.self, forKey: .addQuorumMember)
    {
      try operationCheckAndSet(.addQuorumMember(addQuorumMember))
    }
    if let removeQuorumMember = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.RemoveQuorumMember?.self, forKey: .removeQuorumMember)
    {
      try operationCheckAndSet(.removeQuorumMember(removeQuorumMember))
    }
    if let refreshSingleTenantHsmInstance = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.RefreshSingleTenantHsmInstance?.self,
      forKey: .refreshSingleTenantHsmInstance)
    {
      try operationCheckAndSet(.refreshSingleTenantHsmInstance(refreshSingleTenantHsmInstance))
    }
    if let upgradeKeyTrust = try container.decodeIfPresent(
      SingleTenantHsmInstanceProposal.UpgradeKeyTrust?.self, forKey: .upgradeKeyTrust)
    {
      try operationCheckAndSet(.upgradeKeyTrust(upgradeKeyTrust))
    }
    self.operation = operation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.failureReason, forKey: .failureReason)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encodeIfPresent(self.purgeTime, forKey: .purgeTime)

    if let choice = self.approvalParameters {
      switch choice {
      case .quorumParameters(let value):
        try container.encode(value, forKey: .quorumParameters)
      case .requiredActionQuorumParameters(let value):
        try container.encode(value, forKey: .requiredActionQuorumParameters)
      }
    }

    if let choice = self.expiration {
      switch choice {
      case .expireTime(let value):
        try container.encode(value, forKey: .expireTime)
      case .ttl(let value):
        try container.encode(value, forKey: .ttl)
      }
    }

    if let choice = self.operation {
      switch choice {
      case .registerTwoFactorAuthKeys(let value):
        try container.encode(value, forKey: .registerTwoFactorAuthKeys)
      case .disableSingleTenantHsmInstance(let value):
        try container.encode(value, forKey: .disableSingleTenantHsmInstance)
      case .enableSingleTenantHsmInstance(let value):
        try container.encode(value, forKey: .enableSingleTenantHsmInstance)
      case .deleteSingleTenantHsmInstance(let value):
        try container.encode(value, forKey: .deleteSingleTenantHsmInstance)
      case .addQuorumMember(let value):
        try container.encode(value, forKey: .addQuorumMember)
      case .removeQuorumMember(let value):
        try container.encode(value, forKey: .removeQuorumMember)
      case .refreshSingleTenantHsmInstance(let value):
        try container.encode(value, forKey: .refreshSingleTenantHsmInstance)
      case .upgradeKeyTrust(let value):
        try container.encode(value, forKey: .upgradeKeyTrust)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Parameters of quorum approval for the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public struct QuorumParameters: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The required numbers of approvers. This is the M value used
    /// for M of N quorum auth. It is less than the number of public keys.
    public var requiredApproverCount: Swift.Int32 = Swift.Int32()

    /// Output only. The challenges to be signed by 2FA keys for quorum auth. M
    /// of N of these challenges are required to be signed to approve the
    /// operation.
    public var challenges: [Challenge] = []

    /// Output only. The public keys associated with the 2FA keys that have
    /// already approved the
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// by signing the challenge.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    public var approvedTwoFactorPublicKeyPems: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QuorumParameters`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QuorumParameters().with { $0.requiredApproverCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let requiredApproverCount = CodingKeys(stringValue: "requiredApproverCount")
      static let challenges = CodingKeys(stringValue: "challenges")
      static let approvedTwoFactorPublicKeyPems = CodingKeys(
        stringValue: "approvedTwoFactorPublicKeyPems")

      static let _knownKeys: Set<Swift.String> = [
        "requiredApproverCount",
        "challenges",
        "approvedTwoFactorPublicKeyPems",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .requiredApproverCount)
      {
        self.requiredApproverCount = value
      }
      if let value = try container.decodeIfPresent([Challenge].self, forKey: .challenges) {
        self.challenges = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .approvedTwoFactorPublicKeyPems)
      {
        self.approvedTwoFactorPublicKeyPems = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.requiredApproverCount, forKey: .requiredApproverCount)
      try container.encode(self.challenges, forKey: .challenges)
      try container.encode(
        self.approvedTwoFactorPublicKeyPems, forKey: .approvedTwoFactorPublicKeyPems)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.QuorumParameters"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters for an approval that has both required challenges and a
  /// quorum.
  public struct RequiredActionQuorumParameters: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. A list of specific challenges that must be signed.
    /// For some operations, this will contain a single challenge.
    public var requiredChallenges: [Challenge] = []

    /// Output only. The required number of quorum approvers. This is the M value
    /// used for M of N quorum auth. It is less than the number of public keys.
    public var requiredApproverCount: Swift.Int32 = Swift.Int32()

    /// Output only. The challenges to be signed by 2FA keys for quorum auth. M
    /// of N of these challenges are required to be signed to approve the
    /// operation.
    public var quorumChallenges: [Challenge] = []

    /// Output only. The public keys associated with the 2FA keys that have
    /// already approved the
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// by signing the challenge.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    public var approvedTwoFactorPublicKeyPems: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RequiredActionQuorumParameters`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RequiredActionQuorumParameters().with { $0.requiredChallenges = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let requiredChallenges = CodingKeys(stringValue: "requiredChallenges")
      static let requiredApproverCount = CodingKeys(stringValue: "requiredApproverCount")
      static let quorumChallenges = CodingKeys(stringValue: "quorumChallenges")
      static let approvedTwoFactorPublicKeyPems = CodingKeys(
        stringValue: "approvedTwoFactorPublicKeyPems")

      static let _knownKeys: Set<Swift.String> = [
        "requiredChallenges",
        "requiredApproverCount",
        "quorumChallenges",
        "approvedTwoFactorPublicKeyPems",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Challenge].self, forKey: .requiredChallenges) {
        self.requiredChallenges = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .requiredApproverCount)
      {
        self.requiredApproverCount = value
      }
      if let value = try container.decodeIfPresent([Challenge].self, forKey: .quorumChallenges) {
        self.quorumChallenges = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .approvedTwoFactorPublicKeyPems)
      {
        self.approvedTwoFactorPublicKeyPems = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.requiredChallenges, forKey: .requiredChallenges)
      try container.encode(self.requiredApproverCount, forKey: .requiredApproverCount)
      try container.encode(self.quorumChallenges, forKey: .quorumChallenges)
      try container.encode(
        self.approvedTwoFactorPublicKeyPems, forKey: .approvedTwoFactorPublicKeyPems)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Register 2FA keys for the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
  /// This operation requires all Challenges to be signed by 2FA keys. The
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] must
  /// be in the
  /// [PENDING_TWO_FACTOR_AUTH_REGISTRATION][google.cloud.kms.v1.SingleTenantHsmInstance.State.PENDING_TWO_FACTOR_AUTH_REGISTRATION]
  /// state to perform this operation.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.PENDING_TWO_FACTOR_AUTH_REGISTRATION]: <doc:SingleTenantHsmInstance/State/pendingTwoFactorAuthRegistration>
  public struct RegisterTwoFactorAuthKeys: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The required numbers of approvers to set for the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// This is the M value used for M of N quorum auth. Must be greater than or
    /// equal to 2 and less than or equal to
    /// [total_approver_count][google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]
    /// - 1.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]: <doc:SingleTenantHsmInstance/QuorumAuth/totalApproverCount>
    public var requiredApproverCount: Swift.Int32 = Swift.Int32()

    /// Required. The public keys associated with the 2FA keys for M of N quorum
    /// auth. Public keys must be associated with RSA 2048 keys.
    public var twoFactorPublicKeyPems: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RegisterTwoFactorAuthKeys`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RegisterTwoFactorAuthKeys().with { $0.requiredApproverCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let requiredApproverCount = CodingKeys(stringValue: "requiredApproverCount")
      static let twoFactorPublicKeyPems = CodingKeys(stringValue: "twoFactorPublicKeyPems")

      static let _knownKeys: Set<Swift.String> = [
        "requiredApproverCount",
        "twoFactorPublicKeyPems",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .requiredApproverCount)
      {
        self.requiredApproverCount = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .twoFactorPublicKeyPems)
      {
        self.twoFactorPublicKeyPems = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.requiredApproverCount, forKey: .requiredApproverCount)
      try container.encode(self.twoFactorPublicKeyPems, forKey: .twoFactorPublicKeyPems)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RegisterTwoFactorAuthKeys"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Disable the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]. The
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] must
  /// be in the
  /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state to
  /// perform this operation.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
  public struct DisableSingleTenantHsmInstance: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DisableSingleTenantHsmInstance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DisableSingleTenantHsmInstance().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.DisableSingleTenantHsmInstance"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Enable the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]. The
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] must
  /// be in the
  /// [DISABLED][google.cloud.kms.v1.SingleTenantHsmInstance.State.DISABLED]
  /// state to perform this operation.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.DISABLED]: <doc:SingleTenantHsmInstance/State/disabled>
  public struct EnableSingleTenantHsmInstance: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EnableSingleTenantHsmInstance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EnableSingleTenantHsmInstance().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.EnableSingleTenantHsmInstance"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Delete the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
  /// Deleting a
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] will
  /// make all [CryptoKeys][google.cloud.kms.v1.CryptoKey] attached to the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
  /// unusable. The
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] must
  /// not be in the
  /// [DELETING][google.cloud.kms.v1.SingleTenantHsmInstance.State.DELETING] or
  /// [DELETED][google.cloud.kms.v1.SingleTenantHsmInstance.State.DELETED] state
  /// to perform this operation.
  ///
  /// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.DELETED]: <doc:SingleTenantHsmInstance/State/deleted>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.DELETING]: <doc:SingleTenantHsmInstance/State/deleting>
  public struct DeleteSingleTenantHsmInstance: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DeleteSingleTenantHsmInstance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeleteSingleTenantHsmInstance().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.DeleteSingleTenantHsmInstance"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Add a quorum member to the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
  /// This will increase the
  /// [total_approver_count][google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]
  /// by 1. The
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] must
  /// be in the
  /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state to
  /// perform this operation.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]: <doc:SingleTenantHsmInstance/QuorumAuth/totalApproverCount>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
  public struct AddQuorumMember: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The public key associated with the 2FA key for the new quorum
    /// member to add. Public keys must be associated with RSA 2048 keys.
    public var twoFactorPublicKeyPem: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AddQuorumMember`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AddQuorumMember().with { $0.twoFactorPublicKeyPem = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let twoFactorPublicKeyPem = CodingKeys(stringValue: "twoFactorPublicKeyPem")

      static let _knownKeys: Set<Swift.String> = [
        "twoFactorPublicKeyPem"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .twoFactorPublicKeyPem)
      {
        self.twoFactorPublicKeyPem = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.twoFactorPublicKeyPem, forKey: .twoFactorPublicKeyPem)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.AddQuorumMember"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Remove a quorum member from the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
  /// This will reduce
  /// [total_approver_count][google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]
  /// by 1. The
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] must
  /// be in the
  /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state to
  /// perform this operation.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]: <doc:SingleTenantHsmInstance/QuorumAuth/totalApproverCount>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
  public struct RemoveQuorumMember: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The public key associated with the 2FA key for the quorum
    /// member to remove. Public keys must be associated with RSA 2048 keys.
    public var twoFactorPublicKeyPem: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RemoveQuorumMember`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RemoveQuorumMember().with { $0.twoFactorPublicKeyPem = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let twoFactorPublicKeyPem = CodingKeys(stringValue: "twoFactorPublicKeyPem")

      static let _knownKeys: Set<Swift.String> = [
        "twoFactorPublicKeyPem"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .twoFactorPublicKeyPem)
      {
        self.twoFactorPublicKeyPem = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.twoFactorPublicKeyPem, forKey: .twoFactorPublicKeyPem)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RemoveQuorumMember"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Refreshes the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
  /// This operation must be performed periodically to keep the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
  /// active. This operation must be performed before
  /// [unrefreshed_duration_until_disable][google.cloud.kms.v1.SingleTenantHsmInstance.unrefreshed_duration_until_disable]
  /// has passed. The
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance] must
  /// be in the
  /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state to
  /// perform this operation.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
  /// [google.cloud.kms.v1.SingleTenantHsmInstance.unrefreshed_duration_until_disable]: <doc:SingleTenantHsmInstance/unrefreshedDurationUntilDisable>
  public struct RefreshSingleTenantHsmInstance: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RefreshSingleTenantHsmInstance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RefreshSingleTenantHsmInstance().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.RefreshSingleTenantHsmInstance"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Promotes a key with the AES_WRAPPING purpose to a trusted wrapping key.
  /// The key must be in the
  /// [ACTIVE][CryptoKeyVersion.CryptoKeyVersionState.ACTIVE] state to perform
  /// this operation.
  public struct UpgradeKeyTrust: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The [name][google.cloud.kms.v1.CryptoKeyVersion.name] of the
    /// [CryptoKeyVersion][google.cloud.kms.v1.CryptoKeyVersion] to promote.
    ///
    /// [google.cloud.kms.v1.CryptoKeyVersion]: <doc:CryptoKeyVersion>
    /// [google.cloud.kms.v1.CryptoKeyVersion.name]: <doc:CryptoKeyVersion/name>
    public var name: Swift.String = Swift.String()

    /// Required. The public key associated with the 2FA key that will sign the
    /// login nonce for this operation.
    public var twoFactorPublicKeyPem: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UpgradeKeyTrust`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UpgradeKeyTrust().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let twoFactorPublicKeyPem = CodingKeys(stringValue: "twoFactorPublicKeyPem")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "twoFactorPublicKeyPem",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .twoFactorPublicKeyPem)
      {
        self.twoFactorPublicKeyPem = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.twoFactorPublicKeyPem, forKey: .twoFactorPublicKeyPem)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal.UpgradeKeyTrust"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The set of states of a
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Not specified.
    case unspecified
    /// The
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// is being created.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    case creating
    /// The
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// is pending approval.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    case pending
    /// The
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// has been approved.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    case approved
    /// The
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// is being executed.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    case running
    /// The
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// has been executed successfully.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    case succeeded
    /// The
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// has failed.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    case failed
    /// The
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// has been deleted and will be purged after the purge_time.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .pending: return 2
      case .approved: return 3
      case .running: return 4
      case .succeeded: return 5
      case .failed: return 6
      case .deleted: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .pending: return "PENDING"
      case .approved: return "APPROVED"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "PENDING": self = .pending
      case "APPROVED": self = .approved
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .pending
      case 3: self = .approved
      case 4: self = .running
      case 5: self = .succeeded
      case 6: self = .failed
      case 7: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .pending: return try container.encode("PENDING")
      case .approved: return try container.encode("APPROVED")
      case .running: return try container.encode("RUNNING")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .deleted: return try container.encode("DELETED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The approval parameters for the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  /// The type of parameters is determined by the operation being proposed.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public enum ApprovalParametersOneOf: Codable, Equatable, Sendable {
    /// Output only. The quorum approval parameters for the
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    indirect case quorumParameters(SingleTenantHsmInstanceProposal.QuorumParameters?)
    /// Output only. Parameters for an approval of a
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// that has both required challenges and a quorum.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    indirect case requiredActionQuorumParameters(
      SingleTenantHsmInstanceProposal.RequiredActionQuorumParameters?)
  }

  /// The expiration of the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
  /// If not set, the
  /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
  /// will expire in 1 day. The maximum expire time is 7 days. The minimum expire
  /// time is 5 minutes.
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
  public enum ExpirationOneOf: Codable, Equatable, Sendable {
    /// The time at which the
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal]
    /// will expire if not approved and executed.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    indirect case expireTime(GoogleWKT.WKTTimestamp?)
    /// Input only. The TTL for the
    /// [SingleTenantHsmInstanceProposal][google.cloud.kms.v1.SingleTenantHsmInstanceProposal].
    /// Proposals will expire after this duration.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstanceProposal]: <doc:SingleTenantHsmInstanceProposal>
    indirect case ttl(GoogleWKT.WKTDuration?)
  }

  /// The operation to perform on the
  /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
  ///
  /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
  public enum OperationOneOf: Codable, Equatable, Sendable {
    /// Register 2FA keys for the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// This operation requires all N Challenges to be signed by 2FA keys. The
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// must be in the
    /// [PENDING_TWO_FACTOR_AUTH_REGISTRATION][google.cloud.kms.v1.SingleTenantHsmInstance.State.PENDING_TWO_FACTOR_AUTH_REGISTRATION]
    /// state to perform this operation.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.PENDING_TWO_FACTOR_AUTH_REGISTRATION]: <doc:SingleTenantHsmInstance/State/pendingTwoFactorAuthRegistration>
    indirect case registerTwoFactorAuthKeys(
      SingleTenantHsmInstanceProposal.RegisterTwoFactorAuthKeys?)
    /// Disable the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// The
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// must be in the
    /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state
    /// to perform this operation.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
    indirect case disableSingleTenantHsmInstance(
      SingleTenantHsmInstanceProposal.DisableSingleTenantHsmInstance?)
    /// Enable the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// The
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// must be in the
    /// [DISABLED][google.cloud.kms.v1.SingleTenantHsmInstance.State.DISABLED]
    /// state to perform this operation.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.DISABLED]: <doc:SingleTenantHsmInstance/State/disabled>
    indirect case enableSingleTenantHsmInstance(
      SingleTenantHsmInstanceProposal.EnableSingleTenantHsmInstance?)
    /// Delete the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// Deleting a
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// will make all [CryptoKeys][google.cloud.kms.v1.CryptoKey] attached to the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// unusable. The
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// must be in the
    /// [DISABLED][google.cloud.kms.v1.SingleTenantHsmInstance.State.DISABLED] or
    /// [PENDING_TWO_FACTOR_AUTH_REGISTRATION][google.cloud.kms.v1.SingleTenantHsmInstance.State.PENDING_TWO_FACTOR_AUTH_REGISTRATION]
    /// state to perform this operation.
    ///
    /// [google.cloud.kms.v1.CryptoKey]: <doc:CryptoKey>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.DISABLED]: <doc:SingleTenantHsmInstance/State/disabled>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.PENDING_TWO_FACTOR_AUTH_REGISTRATION]: <doc:SingleTenantHsmInstance/State/pendingTwoFactorAuthRegistration>
    indirect case deleteSingleTenantHsmInstance(
      SingleTenantHsmInstanceProposal.DeleteSingleTenantHsmInstance?)
    /// Add a quorum member to the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// This will increase the
    /// [total_approver_count][google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]
    /// by 1. The
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// must be in the
    /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state
    /// to perform this operation.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]: <doc:SingleTenantHsmInstance/QuorumAuth/totalApproverCount>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
    indirect case addQuorumMember(SingleTenantHsmInstanceProposal.AddQuorumMember?)
    /// Remove a quorum member from the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// This will reduce
    /// [total_approver_count][google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]
    /// by 1. The
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// must be in the
    /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state
    /// to perform this operation.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.QuorumAuth.total_approver_count]: <doc:SingleTenantHsmInstance/QuorumAuth/totalApproverCount>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
    indirect case removeQuorumMember(SingleTenantHsmInstanceProposal.RemoveQuorumMember?)
    /// Refreshes the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance].
    /// This operation must be performed periodically to keep the
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// active. This operation must be performed before
    /// [unrefreshed_duration_until_disable][google.cloud.kms.v1.SingleTenantHsmInstance.unrefreshed_duration_until_disable]
    /// has passed. The
    /// [SingleTenantHsmInstance][google.cloud.kms.v1.SingleTenantHsmInstance]
    /// must be in the
    /// [ACTIVE][google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE] state
    /// to perform this operation.
    ///
    /// [google.cloud.kms.v1.SingleTenantHsmInstance]: <doc:SingleTenantHsmInstance>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.State.ACTIVE]: <doc:SingleTenantHsmInstance/State/active>
    /// [google.cloud.kms.v1.SingleTenantHsmInstance.unrefreshed_duration_until_disable]: <doc:SingleTenantHsmInstance/unrefreshedDurationUntilDisable>
    indirect case refreshSingleTenantHsmInstance(
      SingleTenantHsmInstanceProposal.RefreshSingleTenantHsmInstance?)
    /// Promotes a key with the AES_WRAPPING purpose to a trusted wrapping key.
    /// The key must be in the
    /// [ACTIVE][CryptoKeyVersion.CryptoKeyVersionState.ACTIVE] state to perform
    /// this operation.
    indirect case upgradeKeyTrust(SingleTenantHsmInstanceProposal.UpgradeKeyTrust?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.kms.v1.SingleTenantHsmInstanceProposal"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
